update run migrations

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -272,19 +272,78 @@ jobs:
             ansible-playbook -i ./.circleci/ansible/inventory.txt ./.circleci/ansible/configure-server.yml
       - destroy-environment:
           workflowID: ${CIRCLE_WORKFLOW_ID:0:7}  
-  run-migrations:
+  # run-migrations:
+  #   docker:
+  #     - image: circleci/node:13.8.0
+  #   steps:
+  #     - checkout
+  #     - install_awscli
+  #     - run:
+  #         name: Run migrations
+  #         command: |
+  #           cd backend
+  #           npm install
+  #           # Run and save the migration output
+  #           npm run migrations > migrations_dump.txt
+  #     - run:
+  #         name: Send migration status to kvdb.io
+  #         command: |  
+  #             cat ~/project/backend/migrations_dump.txt 
+  #             if grep -q "No migrations are pending" ~/project/backend/migrations_dump.txt
+  #             then
+  #                 curl -k https://kvdb.io/FBhp9QgWUKXo5X2kjQmmaV/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+  #             fi
+  #     - destroy-environment:
+  #         workflowID: ${CIRCLE_WORKFLOW_ID:0:7}    
+  #     - revert-migrations:
+  #         workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}      
+    run-migrations:
     docker:
+      # Docker image here that supports NodeJS
       - image: circleci/node:13.8.0
     steps:
+      # Checkout code from git
       - checkout
-      - install_awscli
+      - attach_workspace:
+          at: ~/
+      - restore_cache:
+          key: backend-build
+      - run:
+          name: Install AWS CLI dependencies
+          working_directory: /tmp
+          command: |
+            sudo apt-get update && sudo apt-get install -yy less
+            sudo apt-get install unzip -y
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip awscliv2.zip
+            sudo ./aws/install
+      # - run:
+      #     name: Install dependencies
+      #     command: |
+      #       curl -sL https://rpm.nodesource.com/setup_12.x | bash -
+      #       yum -y install nodejs npm tar gzip jq git
       - run:
           name: Run migrations
+          no_output_timeout: 20m
+          working_directory: ./backend
           command: |
-            cd backend
-            npm install
-            # Run and save the migration output
-            npm run migrations > migrations_dump.txt
+            npm i
+            sudo npm install pm2 -g
+            echo ENVIRONMENT=production > ".env"
+            echo TYPEORM_CONNECTION=postgres >> ".env"
+            echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> ".env"
+            echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> ".env"
+            echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> ".env"
+            echo NODE_ENV=production >> ".env"
+            echo TYPEORM_HOST=$TYPEORM_HOST >> ".env"
+            echo TYPEORM_PORT=$TYPEORM_PORT >> ".env"
+            echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> ".env"
+            echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> ".env"
+            echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> ".env"
+            npm run migrations > migration.log
+            cat migration.log
+            migration_succesful=$(cat migration.log | grep -c "has been executed successfully")
+            if [ $migration_succesful > 0 ]; then exit 0; else exit 1; fi;
       - run:
           name: Send migration status to kvdb.io
           command: |  
@@ -293,10 +352,12 @@ jobs:
               then
                   curl -k https://kvdb.io/FBhp9QgWUKXo5X2kjQmmaV/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
               fi
-      - destroy-environment:
-          workflowID: ${CIRCLE_WORKFLOW_ID:0:7}    
-      - revert-migrations:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}      
+      # Here's where you will add some code to rollback on failure
+      # - run:
+      #     name: Revert migrations
+      #     when: on_fail
+      - revert-migrations
+      - destroy-environment      
 
 #   deploy-frontend:
 #     docker:
